version: '3.8'

services:
  lab-qa-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ADMIN_TOKEN=IAMTHEADMINSENTRY
    volumes:
      - ./logs:/app/logs
      - ./tokens.json:/app/tokens.json
      - ./model_files:/app/model_files
    restart: unless-stopped

networks:
  default:
    name: lab-qa-network
